The Early English Text Society, present, past and future

Anyone who reads Old and Middle English literary texts will be familiar with the mid-brown volumes of the EETS, with the symbol of Alfred's jewel embossed on the front cover. Most of the works attributed to King Alfred or to Aelfric, along with some of those by bishop Wulfstan and much anonymous prose and verse from the pre-Conquest period, are to be found within the Society's three series; all of the surviving medieval drama, most of the Middle English romances, much religious and secular prose and verse including the English works of John Gower, Thomas Hoccleve and most of Caxton's prints all find their place in the publications. Without EETS editions, study of medieval English texts would hardly be possible.

As its name states, EETS was begun as a 'club', and it retains certain features of that even now. It has no physical location, or even office, no paid staff or editors, but books in the Original Series are published in the first place to satisfy subscriptions paid by individuals or institutions. This means that there is need for a regular sequence of new editions, normally one or two per year; achieving that sequence can pose problems for the Editorial Secretary, who may have too few or too many texts ready for publication at any one time. Details on a separate sheet explain how individual (but not institutional) members can choose to take certain back volumes in place of the newly published volumes against their subscriptions. On the same sheet are given details about the very advantageous discount available to individual members on all back numbers. In 1970 a Supplementary Series was begun, a series which only appears occasionally (it currently has 24 volumes within it); some of these are new editions of texts earlier appearing in the main series. Again these volumes are available at publication and later at a substantial discount to members. All these advantages can only be obtained through the Membership Secretary (the books are sent by post); they are not available through bookshops, and such bookstores as carry EETS books have only a very limited selection of the many published.

Editors, who receive no royalties or expenses and who are only very rarely commissioned by the Society, are encouraged to approach the Editorial Secretary with a detailed proposal of the text they wish to suggest to the Society early in their work; interest may be expressed at that point, but before any text is accepted for publication the final typescript must be approved by the Council (a body of some twenty scholars), and then assigned a place in the printing schedule. The Society now has a stylesheet to guide editors in the layout and conventions acceptable within its series. No prescriptive set of editorial principles is laid down, but it is usually expected that the evidence of all relevant medieval copies of the text(s) in question will have been considered, and that the texts edited will be complete whatever their length. Editions are directed at a scholarly readership rather than a popular one; though they normally provide a glossary and notes, no translation is provided.

EETS was founded in 1864 by Frederick James Furnivall, with the help of Richard Morris, Walter Skeat, and others, to bring the mass of unprinted Early English literature within the reach of students. It was also intended to provide accurate texts from which the New (later Oxford) English Dictionary could quote; the ongoing work on the revision of that Dictionary is still heavily dependent on the Society's editions, as are the Middle English Dictionary and the Toronto Dictionary of Old English. In 1867 an Extra Series was started, intended to contain texts already printed but not in satisfactory or readily obtainable editions; this series was discontinued in 1921, and from then on all the Society's editions, apart from the handful in the Supplementary Series described above, were listed and numbered as part of the Original Series. In all the Society has now published some 475 volumes; all except for a very small number (mostly of editions superseded within the series) are available in print. The early history of the Society is only traceable in outline: no details about nineteenth-century membership are available, and the secretarial records of the early twentieth century were largely lost during the second world war. By the 1950s a very large number of the Society's editions were out of print, and finances allowed for only a very limited reprinting programme. Around 1970 an advantageous arrangement was agreed with an American reprint firm to make almost all the volumes available once more whilst maintaining the membership discounts. Though this arrangement was superseded towards the end of the twentieth century and the cost of reprinting has reverted to the Society, as a result of the effort then it has proved possible to keep the bulk of the list in print.

Many comparable societies, with different areas of interest, were founded in the nineteenth century (several of them also by Furnivall); not all have survived, and few have produced as many valuable volumes as EETS. The Society's success continues to depend very heavily on the loyalty of members, and especially on the energy and devotion of a series of scholars who have been involved with the administration of the Society - the amount of time and effort spent by those who over the years have filled the role of Editorial Secretary is immeasurable. Plans for publications for the coming years are well in hand: there are a number of important texts which should be published within the next five years. At present, notably because of the efforts of a series of Executive and Membership Secretaries, the Society's finances are in reasonable shape; but certain trends give concern to the Council. The Society's continuance is dependent on two factors: the first is obviously the supply of scholarly editions suitable to be included in its series; the second is on the maintenance of subscriptions and sales of volumes at a level which will cover the printing and distribution costs of the new and reprinted books. The normal copyright laws cover the Society's volumes. All enquiries about large scale reproduction, whether by photocopying or on the internet, should be directed to the Executive Secretary in the first instance. The Society's continued usefulness depends on its editors and on its ability to maintain its (re)printing programme - and that depends on those who traditionally have become members of the Society. We hope you will maintain your membership, and will encourage both the libraries you use and also other individuals to join. Membership conveys many benefits for you, and for the wider academic community concerned for the understanding of medieval texts.

---
Oxbow (foaled March 26, 2010), an American Thoroughbred racehorse, is best known for winning the second jewel in the United States Triple Crown of Thoroughbred Racing, the 2013 Preakness Stakes. A bay colt who was sired by a winner of the Breeders' Cup Classic and out of a full sister to another Breeders' Cup Classic winner, Oxbow was sold as a yearling at Keeneland for $250,000 and is owned by Brad Kelley of Calumet Farm. He was trained by D. Wayne Lukas and was ridden in his Triple Crown races by Gary Stevens.

Oxbow had a reputation as a front-runner who was difficult to rate during his races. Plagued with frequent turnover in jockeys prior to the Triple Crown series, and often running from poor starting gate post positions, he had only two wins prior to his victory in the Preakness. That success was Calumet Farm's first win in a Triple Crown race in 45 years and breeder Richard Santulli's first win in a Triple Crown classic race. It also was Stevens' first Triple Crown win since 2001, following his return to riding in early 2013 after a seven-year retirement, and Lukas' first Triple Crown win since 2000.

Oxbow's second-place finish in the Belmont Stakes in June made him the third horse that year to reach $1 million in purse wins. Following the Belmont, he was ranked the top three-year-old racehorse in the United States by the National Thoroughbred Racing Association (NTRA). He was pulled up shortly after finishing fourth in the Haskell Invitational, and was found to have suffered a soft tissue injury, was taken out of competition for the remainder of his three-year-old season, and retired in October 2013. He stands at stud for the 2014 breeding season at Taylor Made Stallions in Lexington, Kentucky.

--
Oxbow is a bay horse,[2] marked with an irregularly shaped white star on his forehead and white on his lower lip.[3] He is 16 hands (64 inches, 163 cm) tall.[4] Oxbow was bred by Richard Santulli's New Jersey-based Colts Neck Stables,[5][6][7] and foaled in Kentucky at Burleson Farms.[8] His sire is 1998 Breeders' Cup Classic winner Awesome Again,[2] and his dam is Tizamazing, an unraced full sister to the two-time Breeders' Cup Classic winner Tiznow.[9] Oxbow's win in the Preakness Stakes was the first win in a Triple Crown classic race for Santulli's breeding program.[10]

As a yearling, Oxbow was sent to the Keeneland sales, where he was purchased for $250,000 by bloodstock agent Eddie Kane,[5] acting on behalf of Brad M. Kelley's Bluegrass Hall.[7] In 2012, the Calumet Investment Group bought Calumet Farm and leased it to Kelley,[11][a] who moved his Bluegrass Hall racing operation and 200 horses from his Hurricane Hill farm to the historic Calumet property in early 2013.[14][b] Prior to 2013, Calumet Farm had not had a winning horse in a Triple Crown race since 1968.[14]

Although officially registered with The Jockey Club as a bay, Oxbow has white hairs scattered throughout his coat, therefore his trainer, D. Wayne Lukas, describes him as a roan.[16] Oxbow was listed as "gray/roan" when he was sold as a yearling at Keeneland.[17][c]
Oxbow's racing career began on August 3, 2012, at Saratoga Race Course in an $80,000 maiden race at 5.5 furlongs (0.7 mi; 1.1 km) under jockey Junior Alvarado. Listed at odds of 22–1, he was slow out of the gate and in sixth early on. He took an awkward step going into the turn, and as a result, his jockey pulled him up and he was taken off the track in a horse ambulance. In October, Oxbow was given another chance in a $50,000 maiden race at 7 furlongs (0.9 mi; 1.4 km) at Keeneland Race Course. At 11–1 under jockey Jon Court, he broke sharply and led the field at the quarter-mile post. At the top of the homestretch he was caught by Winning Cause, and ultimately finished fourth with a speed figure of 73.[22] On October 31, he ran in another $50,000 maiden race at seven furlongs at Lukas' home track, Churchill Downs. At 17–1 under jockey Terry Thompson, Oxbow came out of the gate ninth, but as in his previous race, had the lead by the quarter-mile post. He ultimately placed third,[23] with an improved speed figure of 85.[22]

Oxbow's first win was a month later on the undercard of the Clark Handicap, in another $50,000 maiden race at Churchill Downs. He went off as the 2–1 favorite in a race of 7 furlongs (0.9 mi; 1.4 km) with jockey Joe Rocco. He started from the far outside at the tenth post position and broke from the gate in seventh but jumped out to the lead within a few strides and led going into the turn by a half length. Oxbow increased his lead throughout the race and won by almost five lengths,[24] earning a 90 speed figure.[22]

After Oxbow's maiden win, he was flown to Hollywood Park in California to run in the Grade I CashCall Futurity at a mile and one-sixteenth (1,700 m) on a synthetic surface. He was the longest shot in the field at 61–1, and drew the far outside post at number eleven. Ridden by Corey Nakatani, his fifth jockey in five races, Oxbow broke well coming out the gate. He ran close to the front throughout the race, despite losing ground by being four horses wide around the first turn and three wide around the final turn.[22] Oxbow finished fourth, nine lengths back,[25] but earned his first Road to the Kentucky Derby point,[26] and a speed figure of 87.[22]

2013: Three-year-old season[edit]
Oxbow was moved with the rest of Lukas' horses to winter headquarters at Oaklawn Park in Hot Springs, Arkansas.[27] He started his Triple Crown prep season on January 19, 2013, with a win at the Fair Grounds Race Course in New Orleans in the mile and 70-yard (1,672 m) Grade III Lecomte Stakes. Ridden for the second time by Jon Court, he went off as the fourth choice at 5–1 and had a favorable number four post position. He came out of the gate quickly and was the front-runner throughout the race. At the top of the homestretch, he was only a half length in front of the field, but then he drew away and won by more than eleven and a half lengths. Horses he beat that day included Golden Soul, who later placed second in the Kentucky Derby, and I've Struck a Nerve, who Oxbow faced again later in the Risen Star Stakes.[28][29] He earned a speed figure of 94[22] and an additional ten points towards qualification for the Derby.[26] That month, Lukas also contacted veteran Hall of Fame jockey Gary Stevens,[30] who had just returned to racing after a seven-year retirement,[31] and discussed having Stevens ride Oxbow in future races.[30]

"He's not an easy horse to train at all, but the good ones do that sometimes."[32]

—D. Wayne Lukas
Five weeks later, Oxbow was entered in the Grade II mile and one-sixteenth (1,700 m) Risen Star Stakes. Ridden for the third time by Jon Court, Oxbow was assigned the far outside post at number ten, and was the second favorite at 4–1. He broke fifth from the gate, moved to third passing the stands, but lost ground by being five horses wide around the first turn. In the stretch, Oxbow took the lead but could not hold it and finished fourth, although he and the three top-placed horses all ended the race within a length and a half of each other in a blanket finish.[22] The winner was I've Struck a Nerve, at odds of 135–1. Oxbow again progressed in performance, earning a speed figure of 98[22] and five more points toward Derby qualification.[26]

Three weeks later, Lukas entered Oxbow in Oaklawn Park's key preparatory race for the Arkansas Derby, the Grade II Rebel Stakes. For the fourth time in five races, Oxbow started on the far outside at post ten. He went off as the favorite for the second time in his career, at 4–1. Lukas switched Jon Court to ride stablemate Will Take Charge, and Oxbow was given yet another jockey, Mike Smith. Oxbow was third out of the gate. He took the lead down the backstretch and stayed in front until the end of the race where he was narrowly defeated by Will Take Charge. Oxbow lost by half a head, but earned his first triple-digit speed figure at 101,[22][33] along with 20 Derby qualification points.[26] After the Rebel Stakes, Oxbow was ranked as one of the top ten horses in some Triple Crown pre-race polls,[34][35] and secured eligibility to run in the Derby with 36 points.[36]

Four weeks after the Rebel, Oxbow entered his last preparatory race before the Triple Crown campaign, the Grade I Arkansas Derby, held on April 13.[37] This race marked the first time Oxbow was ridden by 50-year-old Stevens,[31] who was Oxbow's seventh jockey in nine races.[6] The horse was the favorite at 3–1, but once again drew an unfavorable, far-outside post at ten.[38] Oxbow came out ninth at the break and was almost seven lengths behind the leader at the start.[22] He had developed a reputation for running in front and wearing out his exercise riders,[39] so Stevens unsuccessfully attempted to rate Oxbow and make him run off the pace, behind other horses.[40][41] Oxbow, described by observers as "very rank",[38] and by Stevens as "pissed off ... [and] upset with me that he didn't get the running style he wanted",[40] was tossing his head and fighting Stevens into the clubhouse turn.[38] After running last at one point in the race, Oxbow improved his position and finished fifth, less than a length behind second-place Frac Daddy.[22] Oxbow earned a speed figure of 90, the same as in his maiden win.[22][42] Stevens viewed his attempt to make Oxbow run off the pace as a mistake. "It just turned out to be a nightmare trip and I take full (responsibility) for that", he said.[31] Lukas agreed, stating, "That will not be in [Stevens'] grandchildren's highlight film".[41]
Kentucky Derby[edit]
Oxbow ran in the Kentucky Derby at Churchill Downs as a 25–1 long shot,[43] ridden by Stevens, who had been on Oxbow in workouts since the Arkansas Derby,[44] and as Lukas said, had "gotten to know the horse a little better throughout the last two weeks".[45] Following the scratch of Black Onyx in post position one, Oxbow had the inside number two post in the field of 19 starters and was closest to the rail. His position was further complicated by being next to Revolutionary with jockey Calvin Borel at number three. Between the size of the field and Borel's well-known preference for riding the rail,[46] Oxbow had to use his speed early to get out front and avoid being pushed into the rail or being hemmed in behind traffic. He broke fifth and was soon close to leader Palace Malice, who ran the second fastest initial quarter- and half-miles in Derby history, a pace described as "suicidal".[47] Oxbow maintained his position near the front, and at the top of the homestretch passed the tired-out speed horses to lead the race for a sixteenth of a mile.[48] He then faded and finished in sixth place, six lengths behind winner Orb,[49] though his performance was still viewed as "respectable"[39] and "promising".[45] Oxbow earned a speed figure of 101, the same as he had in the Rebel,[22] and observers noted that he was the only horse that ran near the front of the pack in the opening half-mile to also finish in the top six;[32] none of the other horses out front early finished better than twelfth.[49]

Preakness Stakes[edit]
"I came into the stretch so loaded. I couldn't believe that no one challenged me ... but when no one did, I said, 'I think everybody's in trouble right now.'"[45]

—Gary Stevens
Oxbow next went to Pimlico Race Course in Baltimore to run in the 2013 Preakness Stakes. In the week prior to the race, he had another workout with Stevens,[50] who stated that it was the "first time [Oxbow] had listened to me", later amending his comments to say, "maybe it's the first time I've listened to him."[51]

Oxbow drew a favorable spot in the gate at post position six,[52] his first good draw since his win in the Lecomte,[6] and kept the same rider for three straight races for the first time in his career. At the start of the race, Will Take Charge veered in and brushed Oxbow, who broke third but took the lead within a few strides and soon led by one and a half lengths.[53] Once in front, Stevens got Oxbow to relax,[39] and they ran the first quarter-mile in 0:23.94, the half mile in 0:48.60, and three-quarters at 1:13:26. Despite the modest pace, what one sportswriter called "lullaby fractions",[30] described by Stevens as "just walking the dog",[30] the colt was one and a half lengths in front at the three-quarter-mile mark.[54]